version: "3.8"

services:
  restapi:
    build:
      context: .
      dockerfile: build/docker/restapi.dockerfile
      target: build
    env_file: ./build/env/restapi.env
    image: restapi_img
    container_name: restapi_cont
    ports:
      - 9999:9999
    command: air -c ./config/.air.toml
    volumes:
      - .:/go-rest-sample
      - ./db/mariadb/dump:/var/dump

  mariadb:
    build:
      context: .
      dockerfile: build/docker/mariadb.dockerfile
    env_file: ./build/env/mariadb.env
    image: mariadb_img
    container_name: mariadb_cont
    ports:
      - 3306:3306
    volumes:
      - mariadb-vol:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./db/mariadb/log:/var/log

volumes:
  mariadb-vol:
