version: "3.8"

services:
  restapi:
    build:
      context: .
      dockerfile: build/docker/restapi.dockerfile
    env_file: ./build/env/restapi.env
    image: restapi-img
    container_name: restapi-cont
    ports:
      - 9999:9999
    command: bash
    tty: true
    volumes:
      - .:/restapi
      - ./db/dump:/var/dump

  db:
    build:
      context: .
      dockerfile: build/docker/db.dockerfile
    env_file: ./build/env/db.env
    image: db-img
    container_name: db-cont
    ports:
      - 3306:3306
    volumes:
      - restapi-db-vol:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/log:/var/log

volumes:
  restapi-db-vol:
