version: "3.8"

services:
  restapi:
    build:
      context: .
      dockerfile: build/docker/dev/restapi.dockerfile
    env_file: ./build/env/restapi.env
    image: restapi-img
    container_name: restapi-cont
    ports:
      - 9999:9999
    command: air # CMD を上書き
    volumes:
      - .:/restapi
      - ./db/mariadb/dump:/var/dump

  mariadb:
    build:
      context: .
      dockerfile: build/docker/dev/mariadb.dockerfile
    env_file: ./build/env/mariadb.env
    image: mariadb-img
    container_name: mariadb-cont
    ports:
      - 3306:3306
    volumes:
      - mariadb-vol:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mariadb/log:/var/log

volumes:
  mariadb-vol:
