pkgname = "userentity"
output = "internal/domain/entity/userentity"
add-global-variants=true

[mysql]
dbname      = "restapi_db"
host        = "mariadb"
port        = 3306
user        = "mysql_user"
pass        = "mysql_pwd"
sslmode     = "false"
blacklist   = []
whitelist   = []